python --version                               [check python version]
pip --version                                  [check pip version]
django-admin --version                         [check django version]
pip install virtualenvwrapper-win              [For virtual envirenment setup create]
mkvirtualenv projectenv(env_name)              [For virtual envirenment create]
workon (env_name)                              [For manually env open by other cmd]
pip install django                             [for django install]
mkdir django_project                           [for create folder]
cd django_project(folder_name)                 [For go folder_name]
django-admin startproject first(project_name)  [for Create project Name]
python manage.py runserver                     [for server run]